### ISSUE TITLE
Where do i put the files?

### ISSUE THREAD

**Issue by Loi447** [MOMIN5/force-op-backdoor-plugin#1]
Im not quite sure where to put the files, i tried launching them, but i was only received with error messages "Package not found" and all

**Comment by MOMIN5** [comment]
hmm, you tried building from src? if so then dont forget to add spigot-api.jar as a dependency

here is the jar file
https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/spigotmc/spigot-api/1.16.4-R0.1-SNAPSHOT/spigot-api-1.16.4-R0.1-20210108.224031-43.jar

lemme know if you need any help
